server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location ^~ /api/identity {
    proxy_pass https://cloud-identity.uitiot.vn/;
    proxy_set_header Host cloud-identity.uitiot.vn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_ssl_server_name on;
  }

  location ^~ /api/compute {
    proxy_pass https://cloud-compute.uitiot.vn/;
    proxy_set_header Host cloud-compute.uitiot.vn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_ssl_server_name on;
  }

  location ^~ /api/network {
    proxy_pass https://cloud-network.uitiot.vn/;
    proxy_set_header Host cloud-network.uitiot.vn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_ssl_server_name on;
  }

  location ^~ /api/load-balancer {
    proxy_pass https://cloud-loadbalancer.uitiot.vn/;
    proxy_set_header Host cloud-loadbalancer.uitiot.vn;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_ssl_server_name on;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}